create schema ds_01;

create table `ds_01`.`t_order_0`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_1`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_2`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_3`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_4`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_5`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_6`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_7`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_8`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_9`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_10`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_11`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_12`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_13`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_14`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_01`.`t_order_15`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

create schema ds_02;

create table `ds_02`.`t_order_0`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_1`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_2`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_3`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_4`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_5`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_6`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_7`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_8`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_9`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_10`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_11`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_12`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_13`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_14`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table `ds_02`.`t_order_15`(`order_id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL,`status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`order_id`) )engine=InnoDB  CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

